# 서버 배포 시 사용할 docker-compose 파일
version: "3"
services:
  voicetape-backend:
    container_name: voicetape-backend
    image: ghcr.io/voicetape/backend:latest
    restart: unless-stopped
    ports:
      - 80:8088
      - 443:8088