# jenkins 실행 시 사용할 docker-compose 파일
version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    user: root
    privileged: true
    restart: unless-stopped
    ports:
      - 80:8080
      - 50000:50000
    platform: linux/amd64
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins:
    external: true